[package]
name = "verus-lock-service"
version = "0.1.0"
edition = "2021"
authors = ["Lokesh Mandarapu <mandarapulokesh61@gmail.com>"]

[dependencies]
vstd = { git = "https://github.com/verus-lang/verus", package = "vstd", optional = true }

[features]
verifier = ["dep:vstd"]
